version: 2.1
jobs:
  build_and_test:
    docker:
      - image: docker:18.09
    steps:
      - add_ssh_keys:
          fingerprints:
            - "dd:6f:07:f7:7e:b0:ab:07:1c:1a:43:ba:a0:a3:b9:6f"
      - run: apk add --no-cache --no-progress make git openssh
      - run:
          name: Keyscan Github (HACK) #https://discuss.circleci.com/t/known-hosts-in-circle-2-0/18544
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - checkout
      - setup_remote_docker
      - run: make test-image
  build_test_and_deploy:
    docker:
      - image: docker:18.09
    steps:
      - add_ssh_keys:
          fingerprints:
            - "dd:6f:07:f7:7e:b0:ab:07:1c:1a:43:ba:a0:a3:b9:6f"
      - run: apk add --no-cache --no-progress make git openssh
      - run:
          name: Keyscan Github (HACK) #https://discuss.circleci.com/t/known-hosts-in-circle-2-0/18544
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - checkout
      - setup_remote_docker
      - run: make test-image
      - deploy:
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
            docker tag prybar:latest replco/prybar:latest
            docker push replco/prybar:latest
            git tag "circleci_pipeline_<< pipeline.number >>_build_${CIRCLE_BUILD_NUM}"
            git push origin "circleci_pipeline_<< pipeline.number >>_build_${CIRCLE_BUILD_NUM}"

workflows:
  ci:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: master
      - build_test_and_deploy:
          context: Docker Hub
          filters:
            branches:
              only:
                - master
